name: admin
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.5.3
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  dio: ^5.3.2
  get_it: ^7.6.2
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  flutter_localization: ^0.2.0
  flutter_offline: ^4.0.0
  skeletonizer: ^1.4.2
  jwt_decode: ^0.3.1
  page_transition: ^2.0.9
  path_provider: ^2.1.3
  flutter_secure_storage: ^9.2.2
  supercharged: ^2.1.1
  url_launcher: ^6.1.14
  avatar_glow: ^3.0.1
  image_picker: ^1.0.4
  loader_overlay: ^4.0.0
  quickalert: ^1.1.0
  persistent_bottom_nav_bar: ^6.2.1
  pinput: ^5.0.0
  font_awesome_flutter: ^10.7.0
  flex_color_scheme: ^7.3.1
  flutter_chat_ui: ^1.6.14
  popup_banner: ^1.0.0
  card_swiper: ^3.0.1
  fluttertoast: ^8.2.8
  dio_cache_interceptor: ^3.5.0
  webview_flutter: ^4.9.0
  dio_http2_adapter: ^2.5.3
  readmore: ^3.0.0
  firebase_core: ^3.6.0
  firebase_messaging: ^15.1.3
  signalr_netcore: ^1.4.0
  auto_route: ^9.2.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/sign_icons/
    - assets/translations/en.json
    - assets/translations/ar.json